github: 
  username: pepibumur
  password: 4w4OU4UAQBoc
  repos: 
    - 
      org_name: teambox
      name: teambox-hosted
      bots:
        - image-bot
    - 
      name: PPiAwesomeButton
      org_name: pepibumur
      bots:
        - image-bot

giphy:
  verion: 
  api_key: dc6zaTOxFJmzC
